USE Театр
GO

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION

SELECT Last_name
FROM Actor
WHERE Actor_id = 9

--WAITFOR DELAY '00:00:07'

SELECT Last_name
FROM Actor
WHERE Actor_id = 9

COMMIT


SELECT Last_name
FROM Actor
WHERE Actor_id = 9

UPDATE Actor
SET Last_name = 'Хрусталева'
WHERE Actor_id = 9