USE Театр
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION
INSERT Specialization (Actor_id, Theatrical_character_id) VALUES (1,2)
COMMIT

