USE Театр
GO

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION 

SELECT  * FROM Specialization
SAVE TRAN A

INSERT Specialization (Actor_id, Theatrical_character_id) VALUES (1,2)
ROLLBACK TRAN  A

SELECT  * FROM Specialization

COMMIT

