ALTER LOGIN Test WITH PASSWORD = 'test'


EXECUTE AS USER = 'Test'
DENY SELECT ON Actor TO Test
GRANT SELECT ON Actor TO Test
REVOKE SELECT ON Actor TO Test
REVERT

REVOKE SELECT ON Actor FROM Test  CASCADE 

CREATE USER Lala WITHOUT LOGIN
DROP USER Lala

EXECUTE AS USER = 'Lala'
SELECT * FROM Actor
REVERT

DENY SELECT ON Adress_view TO Test
REVOKE SELECT ON Adress_view FROM Test
